In [1]:
from torch import nn
import torch 
import math 

In [2]:
# Define the parameters
vocab_size = 10  # Example vocabulary size
embedding_dim = 5  # Dimension of the embedding vectors

# Create the embedding layer
embedding = nn.Embedding(vocab_size, embedding_dim)

# Example input: indices of words/tokens
input_indices = torch.tensor([1, 2, 4, 8])

# Get the embeddings for the input indices
embedded = embedding(input_indices)

In [3]:
embedded*math.sqrt(embedding_dim)

tensor([[ 1.6615,  0.9257,  0.2569, -4.2235, -0.0430],
        [ 1.7068,  2.2455,  0.8781, -0.8528,  3.3354],
        [ 2.0813, -0.3093, -0.1635,  3.5547, -2.1924],
        [-2.9115, -0.8228, -1.9628,  1.8962,  0.9515]], grad_fn=<MulBackward0>)

#### Positional Encoding implementation 

In [2]:
import numpy as np 
import matplotlib.pyplot as plt 

In [13]:
def getPositionEncoding(seq_len, d, n=10000):
    P = np.zeros((seq_len, d))
    for k in range(seq_len):
        for i in np.arange(int(d/2)):
            denominator = np.power(n, 2*i/d)
            P[k, 2*i] = np.sin(k/denominator)
            P[k, 2*i+1] = np.cos(k/denominator)
    return P
 
P = getPositionEncoding(seq_len=10, d=4, n=100)
# print(P)

In [31]:
x = torch.randn((10,512))
pe = torch.zeros(10,512)
position = torch.arange(0,10,dtype=float)
print(position.shape)
position = position.unsqueeze(1)
print(position.shape)

torch.Size([10])
torch.Size([10, 1])


In [32]:
div_term = torch.exp(torch.arange(0,512,2).float()*(-math.log(10000.0)/512))
pe[:,0::2] = torch.sin(position*div_term)

In [2]:
x = torch.randn(1,10,512)

In [3]:
512//8

64

In [4]:
x = x.view(x.shape[0],x.shape[1],8,64)

In [6]:
x.shape

torch.Size([1, 10, 8, 64])

In [25]:
# Original tensor
tensor = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)

# Mask tensor (boolean mask)
mask = torch.tensor([False, True, False, True, False])

# Value to fill where mask is True
value = float('-inf')

# Apply masked_fill
result = tensor.masked_fill(mask, value)

print("Original Tensor:")
print(tensor)
print("\nMask Tensor:")
print(mask)
print("\nResult Tensor after masked_fill:")
print(result)

Original Tensor:
tensor([1., 2., 3., 4., 5.])

Mask Tensor:
tensor([False,  True, False,  True, False])

Result Tensor after masked_fill:
tensor([1., -inf, 3., -inf, 5.])


In [28]:
tensor = tensor.unsqueeze(0)
tensor.softmax(dim=-1), tensor.shape

(tensor([[[0.0117, 0.0317, 0.0861, 0.2341, 0.6364]]]), torch.Size([1, 1, 5]))

In [30]:
10**-5

1e-05